spring.application.name=tasklist
spring.datasource.url=jdbc:postgresql://localhost:5432/tasklist
spring.datasource.username=postgres
spring.datasource.password=Secret45&

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true